// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Lexer.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Lexer {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object lexer=$fix(Lexer.createTransducer());
      $line=6;
      Lexer.testLexer($cast(gold.structures.automaton.ITransducer.class,lexer));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"main",$line);
    }
  }
  public static Object testLexer(ITransducer M) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=12;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=13;
      while (true) {
        if (!($bool(true))) break;
        $line=14;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=15;
        System.out.println($message(new Object[]{"Enter an input string: "}));
        $line=16;
        Object string=$fix($opAdditY(((java.util.Scanner)sc).nextLine()," "));
        $line=17;
        Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,string)));
        $line=18;
        Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
        $line=19;
        System.out.println($message(new Object[]{$opAdditY($opAdditY("The lexer did ",(($bool(result))?(""):("not ")))," accept the string.")}));
        $line=20;
        if ($bool(result)) {
          $line=20;
          System.out.println($message(new Object[]{$opAdditY("Token Stream: ",tokenStream)}));
        }
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"testLexer",$line);
    }
    return $result;
  }
  public static Object names=null;
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=35;
      Object Q=$fix(GCollections.asSet("I","R","RO","ROB","ROBO","ROBOT","ROBOT_","ROBOT_R","V","VA","VAR","VARS","B","BE","BEG","BEGI","BEGIN","E","EN","END","a","as","ass","assi","assig","assign","var","num","m","mo","mov","move","moveI","moveIn","moveInD","moveInDi","moveInDir","moveT","MoveTo","moveTo","moveToT","moveToTh","moveToThe","f","fr","fro","fron","front","b","ba","bac","back","t","tu","tur","turn","l","le","lef","left","r","ri","rig","righ","right","a","ar","aro","arou","aroun","around","f","fa","fac","face","n","no","nor","nort","north","s","so","sou","sout","south","e","ea","eas","east","w","we","wes","west","p","pu","put","pi","pic","pick","B","Ba","Bal","Ball","Ballo","Balloo","Balloon","Balloons","C","Ch","Chi","Chip","Chips","s","sk","ski","skip","o","of","i","if","t","th","the","then","el","els","else","wh","whi","whil","while","d","do","re","rep","repe","repea","repeat","ti","tim","time","fa","fac","faci","facin","facing","c","ca","can","canP","canPu","canPut","canPi","canPic","canPick","canM","canMo","canMov","canMove","n","no","not","Err"));
      $line=48;
      Object \u03A3_0=$fix($opUnionY($opUnionY($opIntvlY('0','9'),$opIntvlY('a','z')),$opIntvlY('A','Z')));
      $line=49;
      Object \u03A3=$fix($opUnionY(\u03A3_0,GCollections.asSet(':',';','(',')',' ',',','\n','\t','_')));
      $line=50;
      Object Out=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=51;
      Object q_0=$fix("I");
      $line=52;
      Object F=$fix(GCollections.asSet("I"));
      $line=53;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(Lexer.class,"\u03B4"),new GMethod(Lexer.class,"g"),new GMethod(Lexer.class,"h")});
      if (true) break $try;
      $line=54;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=57;
      if ($bool($opEqualY(q,"Err"))) {
        $line=57;
        $result="Err";
        if (true) break $try;
      }
      else {
        $line=58;
        if ($opMembrY(\u03C3,GCollections.asSet('(',')',' '))) {
          $line=58;
          $result="I";
          if (true) break $try;
        }
        else {
          $line=59;
          if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'p'))) {
            $line=59;
            $result="p";
            if (true) break $try;
          }
          else {
            $line=60;
            if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'t'))) {
              $line=60;
              $result="t";
              if (true) break $try;
            }
            else {
              $line=61;
              if (($opEqualY(q,"I")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                $line=61;
                $result="Num";
                if (true) break $try;
              }
              else {
                $line=62;
                if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                  $line=62;
                  $result="Num";
                  if (true) break $try;
                }
                else {
                  $line=63;
                  if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                    $line=63;
                    $result="Err";
                    if (true) break $try;
                  }
                  else {
                    $line=65;
                    if (($opEqualY(q,"p")&&$opEqualY(\u03C3,'l'))) {
                      $line=65;
                      $result="pl";
                      if (true) break $try;
                    }
                    else {
                      $line=66;
                      if (($opEqualY(q,"pl")&&$opEqualY(\u03C3,'u'))) {
                        $line=66;
                        $result="plu";
                        if (true) break $try;
                      }
                      else {
                        $line=67;
                        if (($opEqualY(q,"plu")&&$opEqualY(\u03C3,'s'))) {
                          $line=67;
                          $result="plus";
                          if (true) break $try;
                        }
                        else {
                          $line=68;
                          if (($opEqualY(q,"t")&&$opEqualY(\u03C3,'i'))) {
                            $line=68;
                            $result="ti";
                            if (true) break $try;
                          }
                          else {
                            $line=69;
                            if (($opEqualY(q,"ti")&&$opEqualY(\u03C3,'m'))) {
                              $line=69;
                              $result="tim";
                              if (true) break $try;
                            }
                            else {
                              $line=70;
                              if (($opEqualY(q,"tim")&&$opEqualY(\u03C3,'e'))) {
                                $line=70;
                                $result="time";
                                if (true) break $try;
                              }
                              else {
                                $line=71;
                                if (($opEqualY(q,"time")&&$opEqualY(\u03C3,'s'))) {
                                  $line=71;
                                  $result="times";
                                  if (true) break $try;
                                }
                                else {
                                  $line=74;
                                  $result="Id";
                                  if (true) break $try;
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=76;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=81;
      $result="";
      if (true) break $try;
      $line=82;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=85;
      String s=null;
      s=$defaultValue(String.class);
      $line=86;
      s=$cast(String.class,$fix(""));
      $line=88;
      if ((!$opMembrY(q,GCollections.asSet("Err"))&&$opMembrY(\u03C3,GCollections.asSet('(',')',' ')))) {
        $line=89;
        if (!$opMembrY(\u03C3,GCollections.asSet(' '))) {
          $line=89;
          s=$cast(String.class,$fix($invokeMethod(String.class,"valueOf",true,null,new Object[]{\u03C3})));
        }
        $line=90;
        if ($opEqualY(q,"I")) {
          $line=90;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=91;
          if ($opEqualY(q,"plus")) {
            $line=91;
            $result=$opAdditY("+",s);
            if (true) break $try;
          }
          else {
            $line=92;
            if ($opEqualY(q,"times")) {
              $line=92;
              $result=$opAdditY("*",s);
              if (true) break $try;
            }
            else {
              $line=93;
              if ($opEqualY(q,"Num")) {
                $line=93;
                $result=$opAdditY("n",s);
                if (true) break $try;
              }
              else {
                $line=94;
                $result=$opAdditY("v",s);
                if (true) break $try;
              }
            }
          }
        }
      }
      else {
        $line=96;
        $result="";
        if (true) break $try;
      }
      $line=98;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"h",$line);
    }
    return $result;
  }
}
